networks:
  kafkanetwork:
    driver: bridge
    
volumes:
  sqlserver2019data:

services:
  sqlserver2019:
    image: "mcr.microsoft.com/mssql/server:2019-latest" 
    ports:
      - "1433:1433"
    networks:
      - kafkanetwork
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=<YourNewStrong@Passw0rd>"
      - "MSSQL_AGENT_ENABLED=True"
    volumes:
      - sqlserver2019data:/var/opt/mssql

  broker:
    image: bitnami/kafka:4.0
    ports:
      - 29092:29092
    networks:
      - kafkanetwork
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:29092,PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,PLAINTEXT://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.0
    networks:
      - kafkanetwork
    depends_on:
      - broker
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker:9092"

  ksqldb-server:
    image: confluentinc/ksqldb-server:${CONFLUENT_VERSION}
    ports:
      - "8088:8088"
      - "8083:8083"
    networks: 
      - kafkanetwork
    depends_on:
      - broker
      - schema-registry
    volumes:
     - "./debezium-connector-sqlserver/:/usr/share/kafka/plugins/"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8088/healthcheck"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: broker:9092
      KSQL_HOST_NAME: ksqldb-server
      KSQL_KSQL_SERVICE_ID: ksql-connect-cluster
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_CONNECT_WORKER_CONFIG: "/etc/ksqldb/connect.properties"
      KSQL_CONNECT_BOOTSTRAP_SERVERS: 'broker:9092'
      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: 'ksqldb-server'
      KSQL_CONNECT_REST_PORT: 8083
      KSQL_CONNECT_GROUP_ID: ksqldb-kafka-connect-group-01
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: _ksqldb-kafka-connect-group-01-configs
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: _ksqldb-kafka-connect-group-01-offsets
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: _ksqldb-kafka-connect-group-01-status      

      KSQL_CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KSQL_CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      #KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '1'
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
      KSQL_CONNECT_PLUGIN_PATH: '/usr/share/kafka/plugins/'

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    networks: 
      - kafkanetwork
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:9092"
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://schema-registry:8081"
      DYNAMIC_CONFIG_ENABLED: 'true'

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:${CONFLUENT_VERSION}
    networks: 
      - kafkanetwork
    depends_on:
      - broker
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

  blazor.sample:
    image: ${DOCKER_REGISTRY-}blazorsample
    build:
      context: .
      dockerfile: Samples/Blazor.Sample/Dockerfile
    networks: 
      - kafkanetwork
    environment:
      ksqlDb__Url: "http://ksqldb-server:8088"
      ConnectionStrings__DefaultConnection: "Server=sqlserver2019,1433;User Id = SA;Password=<YourNewStrong@Passw0rd>;Initial Catalog = Sensors;MultipleActiveResultSets=true;TrustServerCertificate=true"
    depends_on:
      ksqldb-server:
        condition: service_healthy
