name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Clean
      run: dotnet clean ksqlDb.RestApi.Client.sln --configuration Release && dotnet nuget locals all --clear
    - name: Install dependencies
      run: dotnet restore ksqlDb.RestApi.Client.sln
    - name: Build with dotnet
      run: dotnet build ksqlDb.RestApi.Client.sln --configuration Release
    
    # Test
    - name: Execute ksqlDb RestApi Client Unit Tests
      run: dotnet test ./Tests/ksqlDB.RestApi.Client.Tests/ksqlDb.RestApi.Client.Tests.csproj
